import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  Locale _currentLocale = const Locale('en');
  
  Locale get currentLocale => _currentLocale;

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('languageCode') ?? 'en';
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    _currentLocale = Locale(languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('languageCode', languageCode);
    notifyListeners();
  }

  String translate(String key) {
    final Map<String, Map<String, String>> localizedStrings = {
      'en': {
        'profile_title': 'Profile & Settings',
        'edit': 'EDIT',
        'save': 'SAVE',
        'name': 'Name',
        'email': 'Email',
        'phone': 'Phone',
        'pro_member': 'PRO MEMBER',
        'bookings': 'BOOKINGS',
        'wallet': 'WALLET',
        'teams': 'TEAMS',
        'win_rate': 'WIN RATE',
        'orders': 'ORDERS',
        'level': 'LEVEL',
        'matches': 'MATCHES',
        'streak': 'STREAK',
        'total_xp': 'TOTAL XP',
        'favorite': 'FAVORITE',
        'achievements': 'ACHIEVEMENTS',
        'player_statistics': 'PLAYER STATISTICS',
        'settings': 'SETTINGS',
        'notifications': 'Notifications',
        'privacy_security': 'Privacy & Security',
        'language': 'Language',
        'help_support': 'Help & Support',
        'about': 'About',
        'booking_history': 'BOOKING HISTORY',
        'tap_to_add': 'Tap to add',
        'games': 'games',
        'days': 'days',
        'no_bookings': 'No bookings yet',
        'total': 'Total',
        'sport_breakdown': 'SPORT BREAKDOWN',
        'manage_notifications': 'Manage notification preferences',
        'manage_privacy': 'Manage your privacy settings',
        'get_help': 'Get help and contact support',
        'app_version': 'App version and information',
        'logout': 'Log Out',
        'stat_total_bookings': 'Total Bookings',
        'stat_matches_played': 'Matches Played',
        'stat_matches_won': 'Matches Won',
        'stat_win_rate': 'Win Rate',
        'stat_total_spent': 'Total Spent',
        'stat_current_streak': 'Current Streak',
        'stat_longest_streak': 'Longest Streak',
      },
      'hi': {
        'profile_title': 'प्रोफ़ाइल और सेटिंग्स',
        'edit': 'संपादित करें',
        'save': 'सहेजें',
        'name': 'नाम',
        'email': 'ईमेल',
        'phone': 'फ़ोन',
        'pro_member': 'प्रो सदस्य',
        'bookings': 'बुकिंग',
        'wallet': 'वॉलेट',
        'teams': 'टीमें',
        'win_rate': 'जीत दर',
        'orders': 'ऑर्डर',
        'level': 'स्तर',
        'matches': 'मैच',
        'streak': 'स्टाक',
        'total_xp': 'कुल XP',
        'favorite': 'पसंदीदा',
        'achievements': 'उपलब्धियां',
        'player_statistics': 'खिलाड़ी आँकड़े',
        'settings': 'सेटिंग्स',
        'notifications': 'सूचनाएं',
        'privacy_security': 'गोपनीयता और सुरक्षा',
        'language': 'भाषा',
        'help_support': 'सहायता और समर्थन',
        'about': 'बारे में',
        'booking_history': 'बुकिंग इतिहास',
        'tap_to_add': 'जोड़ने के लिए टैप करें',
        'games': 'खेल',
        'days': 'दिन',
        'no_bookings': 'कोई बुकिंग नहीं',
        'total': 'कुल',
        'sport_breakdown': 'खेल विश्लेषण',
        'manage_notifications': 'सूचना प्राथमिकताएं प्रबंधित करें',
        'manage_privacy': 'अपनी गोपनीयता सेटिंग्स प्रबंधित करें',
        'get_help': 'सहायता प्राप्त करें और समर्थन से संपर्क करें',
        'app_version': 'ऐप संस्करण और जानकारी',
        'logout': 'लॉग आउट',
        'stat_total_bookings': 'कुल बुकिंग',
        'stat_matches_played': 'खेले गए मैच',
        'stat_matches_won': 'जीते गए मैच',
        'stat_win_rate': 'जीत दर',
        'stat_total_spent': 'कुल खर्च',
        'stat_current_streak': 'वर्तमान लकीर',
        'stat_longest_streak': 'सबसे लंबी लकीर',
      },
      'ta': {
        'profile_title': 'சுயவிவரம் & அமைப்புகள்',
        'edit': 'திருந்துக',
        'save': 'சேமி',
        'name': 'பெயர்',
        'email': 'மின்னஞ்சல்',
        'phone': 'தொலைபேசி',
        'pro_member': 'ப்ரோ உறுப்பினர்',
        'bookings': 'முன்பதிவுகள்',
        'wallet': 'பணப்பை',
        'teams': 'அணிகள்',
        'win_rate': 'வெற்றி விகிதம்',
        'orders': 'ஆர்டர்கள்',
        'level': 'நிலை',
        'matches': 'போட்டிகள்',
        'streak': 'தொடர்ச்சி',
        'total_xp': 'மொத்த XP',
        'favorite': 'பிடித்தவை',
        'achievements': 'சாதனைகள்',
        'player_statistics': 'வீரர் புள்ளிவிவரங்கள்',
        'settings': 'அமைப்புகள்',
        'notifications': 'அறிவிப்புகள்',
        'privacy_security': 'தனியுரிமை மற்றும் பாதுகாப்பு',
        'language': 'மொழி',
        'help_support': 'உதவி மற்றும் ஆதரவு',
        'about': 'பற்றி',
        'booking_history': 'முன்பதிவு வரலாறு',
        'tap_to_add': 'சேர்க்க தட்டவும்',
        'games': 'விளையாட்டுகள்',
        'days': 'நாட்கள்',
        'no_bookings': 'முன்பதிவுகள் இல்லை',
        'total': 'மொத்தம்',
        'sport_breakdown': 'விளையாட்டு பிரிவுகள்',
        'manage_notifications': 'அறிவிப்பு விருப்பங்களை நிர்வகிக்கவும்',
        'manage_privacy': 'உங்கள் தனியுரிமை அமைப்புகளை நிர்வகிக்கவும்',
        'get_help': 'உதவி பெற மற்றும் ஆதரவைத் தொடர்பு கொள்ள',
        'app_version': 'செயலி பதிப்பு மற்றும் தகவல்',
        'logout': 'வெளியேறு',
        'stat_total_bookings': 'மொத்த முன்பதிவுகள்',
        'stat_matches_played': 'விளையாடிய போட்டிகள்',
        'stat_matches_won': 'வென்ற போட்டிகள்',
        'stat_win_rate': 'வெற்றி விகிதம்',
        'stat_total_spent': 'மொத்த செலவு',
        'stat_current_streak': 'தற்போதைய தொடர்ச்சி',
        'stat_longest_streak': 'மிக நீண்ட தொடர்ச்சி',
      },
       'te': {
        'profile_title': 'ప్రొఫైల్ & సెట్టింగ్‌లు',
        'edit': 'సవరించు',
        'save': 'సేవ్',
        'name': 'పేరు',
        'email': 'ఇ-మెయిల్',
        'phone': 'ఫోన్',
        'pro_member': 'ప్రో సభ్యుడు',
        'bookings': 'బుకింగ్‌లు',
        'wallet': 'వాలెట్',
        'teams': 'జట్లు',
        'win_rate': 'విజయం రేటు',
        'orders': 'ఆర్డర్‌లు',
        'level': 'స్థాయి',
        'matches': 'మ్యాచ్‌లు',
        'streak': 'స్ట్రీక్',
        'total_xp': 'మొత్తం XP',
        'favorite': 'ఇష్టమైనవి',
        'achievements': 'విజయాలు',
        'player_statistics': 'ప్లేయర్ గణాంకాలు',
        'settings': 'సెట్టింగ్‌లు',
        'notifications': 'నోటిఫికేషన్‌లు',
        'privacy_security': 'గోప్యత & భద్రత',
        'language': 'భాష',
        'help_support': 'సహాయం & మద్దతు',
        'about': 'గురించి',
        'booking_history': 'బుకింగ్ చరిత్ర',
        'tap_to_add': 'జోడించడానికి నొక్కండి',
        'games': 'ఆటలు',
        'days': 'రోజులు',
        'no_bookings': 'ఇంకా బుకింగ్‌లు లేవు',
        'total': 'మొత్తం',
        'sport_breakdown': 'క్రీడా విశ్లేషణ',
        'manage_notifications': 'నోటిఫికేషన్ ప్రాధాన్యతలను నిర్వహించండి',
        'manage_privacy': 'మీ గోప్యతా సెట్టింగ్‌లను నిర్వహించండి',
        'get_help': 'సహాయం పొందండి మరియు మద్దతును సంప్రదించండి',
        'app_version': 'యాప్ వెర్షన్ మరియు సమాచారం',
        'logout': 'లాగ్ అవుట్',
        'stat_total_bookings': 'మొత్తం బుకింగ్‌లు',
        'stat_matches_played': 'ఆడిన మ్యాచ్‌లు',
        'stat_matches_won': 'గెలిచిన మ్యాచ్‌లు',
        'stat_win_rate': 'విజయం రేటు',
        'stat_total_spent': 'మొత్తం ఖర్చు',
        'stat_current_streak': 'ప్రస్తుత స్ట్రీక్',
        'stat_longest_streak': 'అత్యధ్బుత స్ట్రీక్',
      },
      'kn': {
        'profile_title': 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        'edit': 'ತಿದ್ದು',
        'save': 'ಉಳಿಸಿ',
        'name': 'ಹೆಸರು',
        'email': 'ಇಮೇಲ್',
        'phone': 'ದೂರವಾಣಿ',
        'pro_member': 'ಪ್ರೊ ಸದಸ್ಯ',
        'bookings': 'ಬುಕಿಂಗ್‌ಗಳು',
        'wallet': 'ವಾಲೆಟ್',
        'teams': 'ತಂಡಗಳು',
        'win_rate': 'ಗೆಲುವಿನ ದರ',
        'orders': 'ಆರ್ಡರ್‌ಗಳು',
        'level': 'ಹಂತ',
        'matches': 'ಪಂದ್ಯಗಳು',
        'streak': 'ದಿನಗಳು',
        'total_xp': 'ಒಟ್ಟು XP',
        'favorite': 'ಮೆಚ್ಚಿನ',
        'achievements': 'ಸಾಧನೆಗಳು',
        'player_statistics': 'ಆಟಗಾರರ ಅಂಕಿಅಂಶಗಳು',
        'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        'notifications': 'ಸೂಚನೆಗಳು',
        'privacy_security': 'ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ',
        'language': 'ಭಾಷೆ',
        'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
        'about': 'ಕುರಿತು',
        'booking_history': 'ಬುಕಿಂಗ್ ಇತಿಹಾಸ',
        'tap_to_add': 'ಸೇರಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
        'games': 'ಆಟಗಳು',
        'days': 'ದಿನಗಳು',
        'no_bookings': 'ಯಾವುದೇ ಬುಕಿಂಗ್‌ಗಳಿಲ್ಲ',
        'total': 'ಒಟ್ಟು',
        'sport_breakdown': 'ಕ್ರೀಡಾ ವಿಂಗಡಣೆ',
        'manage_notifications': 'ಸೂಚನೆ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        'manage_privacy': 'ನಿಮ್ಮ ಗೌಪ್ಯತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        'get_help': 'ಸಹಾಯ ಪಡೆಯಿರಿ ಮತ್ತು ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ',
        'app_version': 'ಅಪ್ಲಿಕೇಶನ್ ಆವೃತ್ತಿ ಮತ್ತು ಮಾಹಿತಿ',
        'logout': 'ಲಾಗ್ ಔಟ್',
        'stat_total_bookings': 'ಒಟ್ಟು ಬುಕಿಂಗ್‌ಗಳು',
        'stat_matches_played': 'ಆಡಿದ ಪಂದ್ಯಗಳು',
        'stat_matches_won': 'ಗೆದ್ದ ಪಂದ್ಯಗಳು',
        'stat_win_rate': 'ಗೆಲುವಿನ ದರ',
        'stat_total_spent': 'ಒಟ್ಟು ಖರ್ಚು',
        'stat_current_streak': 'ಪ್ರಸ್ತುತ ಸ್ಟ್ರೀಕ್',
        'stat_longest_streak': 'ದೀರ್ಘಾವಧಿಯ ಸ್ಟ್ರೀಕ್',
      },
      'ml': {
        'profile_title': 'പ്രൊഫൈലും ക്രമീകരണങ്ങളും',
        'edit': 'തിരുത്തുക',
        'save': 'സംരക്ഷിക്കുക',
        'name': 'പേര്',
        'email': 'ഇമെയിൽ',
        'phone': 'ഫോൺ',
        'pro_member': 'പ്രോ അംഗം',
        'bookings': 'ബുക്കിംഗുകൾ',
        'wallet': 'വാലറ്റ്',
        'teams': 'ടീമുകൾ',
        'win_rate': 'വിജയ നിരക്ക്',
        'orders': 'ഓർഡറുകൾ',
        'level': 'ലെവൽ',
        'matches': 'മത്സരങ്ങൾ',
        'streak': 'സ്ട്രീക്ക്',
        'total_xp': 'ആകെ XP',
        'favorite': 'പ്രിയപ്പെട്ടത്',
        'achievements': 'നേട്ടങ്ങൾ',
        'player_statistics': 'കളിക്കാരുടെ സ്ഥിതിവിവരക്കണക്കുകൾ',
        'settings': 'ക്രമീകരണങ്ങൾ',
        'notifications': 'അറിയിപ്പുകൾ',
        'privacy_security': 'സ്വകാര്യതയും സുരക്ഷയും',
        'language': 'ഭാഷ',
        'help_support': 'സഹായവും പിന്തുണയും',
        'about': 'കുറിച്ച്',
        'booking_history': 'ബുക്കിംഗ് ചരിത്രം',
        'tap_to_add': 'ചേർക്കാൻ ടാപ്പുചെയ്യുക',
        'games': 'കളികൾ',
        'days': 'ദിവസങ്ങൾ',
        'no_bookings': 'ബുക്കിംഗുകളൊന്നുമില്ല',
        'total': 'ആകെ',
        'sport_breakdown': 'കായിക വിഭാഗങ്ങൾ',
        'manage_notifications': 'അറിയിപ്പ് മുൻഗണനകൾ നിയന്ത്രിക്കുക',
        'manage_privacy': 'നിങ്ങളുടെ സ്വകാര്യതാ ക്രമീകരണങ്ങൾ നിയന്ത്രിക്കുക',
        'get_help': 'സഹായം നേടുക, പിന്തുണയുമായി ബന്ധപ്പെടുക',
        'app_version': 'ആപ്പ് പതിപ്പും വിവരങ്ങളും',
        'logout': 'ലോഗ് ഔട്ട്',
        'stat_total_bookings': 'ആകെ ബുക്കിംഗുകൾ',
        'stat_matches_played': 'കളിച്ച മത്സരങ്ങൾ',
        'stat_matches_won': 'ജയിച്ച മത്സരങ്ങൾ',
        'stat_win_rate': 'വിജയ നിരക്ക്',
        'stat_total_spent': 'ആകെ ചെലവ്',
        'stat_current_streak': 'നിലവിലെ സ്ട്രീക്ക്',
        'stat_longest_streak': 'ഏറ്റവും ദൈർഘ്യമേറിയ സ്ട്രീക്ക്',
      },
    };

    return localizedStrings[_currentLocale.languageCode]?[key] ?? localizedStrings['en']![key] ?? key;
  }
}
