// File generated by FlutterFire CLI (edited manually to add iOS/macOS and fix web appId).
// Re-run `flutterfire configure` if you add a new Firebase app in the console.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run `flutterfire configure` to add a Windows app.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure` to add a Linux app.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: The `appId` values below must match what the Firebase console issues
  // for each platform (Project settings → General → Your apps). Run
  // `flutterfire configure` to regenerate this file with correct values.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-1pN_CgHsOqJN--ShyrH7BfwrTTSPzU',
    // TODO: replace with the real web appId from Firebase console; the previous
    // value ended in zeros and caused the web app to misregister.
    appId: '1:721347779964:web:0000000000000000000000',
    messagingSenderId: '721347779964',
    projectId: 'playtime-d9b83',
    authDomain: 'playtime-d9b83.firebaseapp.com',
    storageBucket: 'playtime-d9b83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-1pN_CgHsOqJN--ShyrH7BfwrTTSPzU',
    appId: '1:721347779964:android:8ebc174de14d07b2bed8f9',
    messagingSenderId: '721347779964',
    projectId: 'playtime-d9b83',
    storageBucket: 'playtime-d9b83.firebasestorage.app',
  );

  // iOS Firebase app registered for the com.playtime.zekto bundle.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqow6ib54m6I5V9EYx6prPOUlOXZnJ65U',
    appId: '1:721347779964:ios:accc49cf31a8f7b1bed8f9',
    messagingSenderId: '721347779964',
    projectId: 'playtime-d9b83',
    storageBucket: 'playtime-d9b83.firebasestorage.app',
    iosBundleId: 'com.playtime.zekto',
    iosClientId:
        '721347779964-5scrjpjpr2kd8hbqr5t6rbevkhqonae1.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-1pN_CgHsOqJN--ShyrH7BfwrTTSPzU',
    appId: '1:721347779964:ios:0000000000000000000000',
    messagingSenderId: '721347779964',
    projectId: 'playtime-d9b83',
    storageBucket: 'playtime-d9b83.firebasestorage.app',
    iosBundleId: 'com.playtime.zekto',
  );
}
